spring: 
  profiles: 
    active: 
    - dev

---
server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 20
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.south.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: dept-8001
    prefer-ip-address: true         # 访问路径可以显示ip地址
    
# 配置服务提示信息
info:
  app.name: south-microservicecloud-dev
  company.name: www.south.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server: 
  port: 8001
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 20
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.south.springcloud.entity
  mapper-locations:
  - classpath: mybatis/mapper/**/*.xml
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: dept-8001
    prefer-ip-address: true         # 访问路径可以显示ip地址
    
# 配置服务提示信息
info:
  app.name: south-microservicecloud-test
  company.name: www.south.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$